#!/usr/bin/env bash

set -e

go clean "${1}"
go build "${1}"

#stty echo

dlv debug --headless --api-version=2 --listen=127.0.0.1:43000 "${1}" &
sleep 2s
printf "\n"

dlv_pid="$(jobs -p %dlv)"
printf "\n"

dlv connect 127.0.0.1:43000
printf "\n"

kill -9 "${dlv_pid}"
